# Generated by Django 3.2 on 2022-03-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
