# Generated by Django 3.2 on 2022-04-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20220318_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='language',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='assign',
            name='Assignment',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='CourseName',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
    ]
