# Generated by Django 3.2 on 2022-04-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_auto_20220406_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='studentss',
            new_name='students',
        ),
    ]
