# Generated by Django 3.2 on 2022-04-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_rename_studentss_item_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='assigns',
        ),
        migrations.RemoveField(
            model_name='item',
            name='students',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
