# Generated by Django 3.2 on 2022-04-10 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_auto_20220407_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='assign',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='front.item'),
        ),
        migrations.AddField(
            model_name='assign',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
