# Generated by Django 3.2 on 2022-02-24 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('idSubject', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSubject', models.CharField(max_length=5)),
                ('assignment', models.CharField(max_length=5)),
                ('score', models.CharField(max_length=6)),
                ('timeIn', models.CharField(max_length=32)),
                ('check', models.BooleanField(default=False)),
                ('error', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(max_length=5)),
                ('score', models.CharField(max_length=6)),
                ('result', models.CharField(max_length=256)),
                ('pathMainFile', models.CharField(max_length=256)),
                ('pathInput', models.CharField(max_length=256)),
                ('pathOutput', models.CharField(max_length=256)),
                ('language', models.CharField(max_length=32)),
                ('format', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=True)),
                ('idSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('idSubject', models.ManyToManyField(blank=True, to='api.Subject')),
            ],
        ),
    ]
